version: "3.6"
services:
  django:
    build: .
    restart: unless-stopped
    environment:
      - SECRET_KEY=23408728djlkjd37nmckdllsorhh377889s900&
    volumes:
        -   .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - djongo-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - djongo-network
volumes:
  db_data:
networks:
  djongo-network: