version: "3.6"
services:
  django:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
volumes:
  db_data:
